In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import transformers
from transformers import LayoutLMForTokenClassification,\
    LayoutLMTokenizer, AdamW, LayoutLMv2Processor, LayoutLMv2ForTokenClassification
# from tensordict import TensorDict
from datasets import load_dataset
import torch
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import ImageDraw, Image
import numpy as np
from tqdm import tqdm
from torch.utils.data import DataLoader, Dataset
import logging
# from torchvision.transforms import PILToTensor

import os 
if 'notebooks' in os.getcwd():
    os.chdir("..")

/users/eleves-a/2022/pedro.silva/few-shot-learning-transformers/.venv/lib64/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
logging.basicConfig(filename='logs/train.log', encoding='utf-8', level=logging.DEBUG)

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [5]:
device

device(type='cuda')

In [6]:
dataset = load_dataset("katanaml/cord", )

# dataset = load_dataset("darentang/sroie")

Repo card metadata block was not found. Setting CardData to empty.


## Creating PyTorch Datasets, DataLoader

In [7]:
processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr")


In [8]:
class SROIE(Dataset):
    def __init__(self, 
                 data,
                 encode : bool = False) -> None:
        super().__init__()

        if encode:
            self.X = []
            for example in tqdm(data):
                X= SROIE.encode(example)
                self.X.append(X)

        else:
            self.X = data

    @staticmethod
    def encode(
        example, 
        max_seq_length = 512, 
        pad_token_box = [0,0,0,0]
    ):
        words = example['words']
        boxes = example['bboxes']
        image = Image.open(example['image_path'])
        word_labels = example['ner_tags']

        encoded_inputs = processor(
            image, 
            words, 
            boxes=boxes, 
            word_labels=word_labels, 
            padding="max_length", 
            truncation=True, 
            return_tensors="pt"
        )

        # token_boxes = []
        # for word, box in zip(words, bboxes):
        #     word_tokens = tokenizer.tokenize(word)
        #     token_boxes.extend([box] * len(word_tokens))

        
        # special_tokens_count = 2 
        # if len(token_boxes) > max_seq_length - special_tokens_count:
        #     token_boxes = token_boxes[: (max_seq_length - special_tokens_count)]

        # # add bounding boxes of cls + sep tokens
        # token_boxes = [[0, 0, 0, 0]] + token_boxes + [[1000, 1000, 1000, 1000]]

        # encoding = tokenizer(' '.join(words), padding='max_length', truncation=True)
        # # Padding of token_boxes up the bounding boxes to the sequence length.
        # input_ids = torch.tensor(tokenizer(' '.join(words), truncation=True)["input_ids"])
        # padding_length = max_seq_length - len(input_ids)
        # token_boxes += [pad_token_box] * padding_length

        # encoding['labels'] = torch.tensor(example['ner_tags'])
        # encoding['bbox'] = torch.tensor(token_boxes)
        # # encoding['input_ids'] = torch.tensor(encoding['input_ids'])
        # encoding['token_type_ids'] = torch.tensor(encoding['token_type_ids'])
        # encoding['attention_mask'] = torch.tensor(encoding['attention_mask'])
        
        return encoded_inputs
    
    def __getitem__(self, index: int):
        return self.X[index]

    def __len__(self):
        return len(self.X)

In [9]:
data = []
for example in tqdm(dataset['train']):
    words = example['words']
    boxes = example['bboxes']
    image = Image.open(example['image_path']).convert("RGB")
    word_labels = example['ner_tags']

    try:
        encoded_inputs = processor(
            image, 
            words, 
            boxes=boxes, 
            word_labels=word_labels, 
            padding="max_length", 
            truncation=True, 
            return_tensors="pt"
        )

        data.append(encoded_inputs)
    except:
        pass

    # assert encoded_inputs.input_ids.shape == torch.Size([512])
    # assert encoded_inputs.attention_mask.shape == torch.Size([512])
    # assert encoded_inputs.token_type_ids.shape == torch.Size([512])
    # assert encoded_inputs.bbox.shape == torch.Size([512, 4])
    # assert encoded_inputs.image.shape == torch.Size([3, 224, 224])
    # assert encoded_inputs.labels.shape == torch.Size([512]) 

  0%|          | 3/800 [00:00<00:33, 23.84it/s]

100%|██████████| 800/800 [00:38<00:00, 20.63it/s]


In [10]:
encoded_inputs.input_ids.shape

torch.Size([1, 512])

In [11]:
df = SROIE(data, encode=False)

In [12]:
dataloader = DataLoader(
    df,
    shuffle=True,
    batch_size= 2
)

In [13]:
example = dataset['train'][0]

In [14]:
unique_rows = []
for row in dataset['train']['ner_tags']:
    unique_rows.append(np.unique(row))

In [15]:
n_labels = np.unique(np.concatenate(unique_rows)).shape[0]

In [16]:
n_labels

23

## Importing model

In [20]:
torch.version.cuda

'11.7'

In [21]:

model = LayoutLMForTokenClassification.from_pretrained(
    'microsoft/layoutlmv2-base-uncased',
    num_labels=n_labels
)
model.to(device)

You are using a model of type layoutlmv2 to instantiate a model of type layoutlm. This is not supported for all configurations of models and can yield errors.
Some weights of LayoutLMForTokenClassification were not initialized from the model checkpoint at microsoft/layoutlmv2-base-uncased and are newly initialized: ['layoutlm.encoder.layer.11.attention.self.query.bias', 'layoutlm.encoder.layer.5.attention.self.value.weight', 'layoutlm.encoder.layer.5.intermediate.dense.bias', 'layoutlm.encoder.layer.11.output.dense.bias', 'layoutlm.encoder.layer.2.attention.self.key.weight', 'layoutlm.encoder.layer.8.attention.self.query.bias', 'layoutlm.encoder.layer.4.attention.output.dense.weight', 'layoutlm.encoder.layer.2.attention.output.dense.weight', 'layoutlm.encoder.layer.9.attention.output.LayerNorm.bias', 'layoutlm.encoder.layer.1.attention.self.query.weight', 'layoutlm.encoder.layer.3.output.LayerNorm.weight', 'layoutlm.encoder.layer.6.output.dense.weight', 'layoutlm.encoder.layer.11.inter

LayoutLMForTokenClassification(
  (layoutlm): LayoutLMModel(
    (embeddings): LayoutLMEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (x_position_embeddings): Embedding(1024, 768)
      (y_position_embeddings): Embedding(1024, 768)
      (h_position_embeddings): Embedding(1024, 768)
      (w_position_embeddings): Embedding(1024, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): LayoutLMEncoder(
      (layer): ModuleList(
        (0-11): 12 x LayoutLMLayer(
          (attention): LayoutLMAttention(
            (self): LayoutLMSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
 

### Number of treinable / non-treinable parameters

In [54]:
print(f'''
    Model Info
    -----------------
    
    Treinable params: {sum(p.numel() for p in model.parameters() if p.requires_grad)}
    Non Treinable params: {sum(p.numel() for p in model.parameters() if not p.requires_grad)}

''')


    Model Info
    -----------------
    
    Treinable params: 199673750
    Non Treinable params: 425152




In [22]:
model(input_ids=input_ids, bbox=bbox, attention_mask=attention_mask, token_type_ids=token_type_ids,
                      labels=labels)

NameError: name 'input_ids' is not defined

In [31]:
optimizer = AdamW(model.parameters(), lr=5e-5)

global_step = 0
num_train_epochs = 4
t_total = len(dataloader) * num_train_epochs # total number of training steps 

#put the model in training mode
model.train()
for epoch in tqdm(range(num_train_epochs)):
  logging.info(f"Epoch: {epoch}")
  running_loss = 0.0
  correct = 0
  for X in (dataloader):
      input_ids = X["input_ids"]\
         .to(device)\
         .squeeze()
      
      bbox = X["bbox"]\
         .to(device)\
         .squeeze()

      attention_mask = X["attention_mask"]\
         .to(device)\
         .squeeze()
      token_type_ids = X["token_type_ids"]\
         .to(device)\
         .squeeze()
      
      labels = X["labels"].to(device)
      image = X["image"]\
         .to(device)\
         .squeeze()

      # forward pass
      outputs = model(
         input_ids=input_ids, 
         bbox=bbox, 
         attention_mask=attention_mask, 
         token_type_ids=token_type_ids,
         labels=labels
      )

      # outputs = model(
      #   input_ids=input_ids, 
      #   bbox=bbox, 
      #   attention_mask=attention_mask, 
      #   token_type_ids=token_type_ids,
      #   image= image,
      #   labels=labels
      # )
      loss = outputs.loss

      running_loss += loss.item()
      predictions = outputs.logits.argmax(-1)
      correct += (predictions == labels).float().sum()

      # backward pass to get the gradients 
      loss.backward()

      # update
      optimizer.step()
      optimizer.zero_grad()
      global_step += 1
  
  logging.info(f"Loss: {running_loss / input_ids.shape[0]}")
  accuracy = 100 * correct / len(data)
  logging.info(f"Training accuracy: {accuracy.item()}", )

  0%|          | 0/4 [00:00<?, ?it/s]

100%|██████████| 4/4 [01:37<00:00, 24.37s/it]


In [37]:
labels

tensor([[[-100,   13, -100,  ..., -100, -100, -100]],

        [[-100,   22, -100,  ..., -100, -100, -100]]], device='cuda:0')

In [36]:
outputs.logits.argmax(-1)

tensor([[ 3,  5,  9,  ...,  3,  3,  7],
        [14, 22, 22,  ..., 14, 14,  3]], device='cuda:0')

In [25]:
outputs = model(
        input_ids=input_ids.squeeze(), 
        bbox=bbox, 
        attention_mask=attention_mask.squeeze(), 
        token_type_ids=token_type_ids.squeeze(),
        # image= image,
        labels=labels
      )

In [77]:
input_ids.shape

torch.Size([2, 1, 512])

In [78]:
bbox.shape

torch.Size([2, 512, 4])

In [79]:
attention_mask.shape

torch.Size([2, 1, 512])

In [80]:
token_type_ids.shape

torch.Size([2, 1, 512])

In [81]:

image.shape

torch.Size([2, 3, 224, 224])

In [86]:
torch.unique(labels)


tensor([-100,    1,    3,    5,    9,   10,   13,   14,   15,   16,   22])